id:
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner:
resource: repository
disabled: false
where:
configuration:
    resourceManagementConfiguration:
        eventResponderTasks:
            - description: Add untriaged label to new issues
              if:
                  - payloadType: Issues
                  - isAction:
                        action: Opened
              then:
                  - addLabel:
                        label: untriaged
