name: GitOps.PullRequestIssueManagement - Scheduled PRs
description: Creates pull requests on a schedule
resource: repository

where:
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: Push to main (scheduled sync)
      frequencies:
      - daily:
          time: 1:00
      - daily:
          time: 9:00
      - daily:
          time: 17:00
      filters: []
      actions:
      - createPullRequest:
          head: smoke-test
          base: main
          title: Merge smoke-test into main
          body: Please don't squash-merge this PR.