id:
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
    - description: Sync API docs to staging
      triggerOnOwnActions: true
      if:
      - payloadType: Pull_Request
      - isAction:
          action: Opened
      - isActivitySender:
          user: microsoft-github-policy-service[bot]
      - titleContains:
          pattern: Merge smoke-test into main
          isRegex: False
      then:
      - addLabel:
          label: ':octocat: auto-merge'

    - description: Sync staging to production
      triggerOnOwnActions: true
      if:
      - payloadType: Pull_Request
      - isAction:
          action: Opened
      - isActivitySender:
          user: microsoft-github-policy-service[bot]
      - titleContains:
          pattern: Merge main into live
          isRegex: False
      then:
      - addLabel:
          label: ':octocat: auto-merge'